### ISSUE TITLE
Need to recreate Python API page for Read the Docs build

### ISSUE THREAD

**Issue by samjwu** [ROCmSoftwarePlatform/hipRAND#27]
**Describe the bug**
#26 This PR standardizes hipRAND documentation builds to use rocm-docs-core and removes the Python API page since steps are not included for building Python API docs for the Read the Docs build yet

**To Reproduce**
1. Run steps in https://github.com/ROCmSoftwarePlatform/hipRAND/blob/9a067f9f91637775fbf5103f5d855ddb8084df08/README.md#how-to-build-documentation to build docs locally
2. Observe the page hosted on Read the Docs is missing the Python API documentation

**Expected behavior**
The Python API page needs to be recreated with the documentation generated for the code

**Comment by mfep** [comment]
Python API documentation page was recreated in #32
