### ISSUE TITLE
tagged release missing for rocm-5.7.1

### ISSUE THREAD

**Issue by BenWibking** [ROCmSoftwarePlatform/hipRAND#88]
There is no tagged release for rocm-5.7.1, unlike all previous releases.

**Comment by pelahi** [comment]
The fact that this wasn't tagged is a bit worrying as I would have thought there was a semi-automate process for taking all the related rocm and hip repositories. Why wasn't a tag produced related to the release of 5.7.1? Could it be that there are packages that have been mistagged as well? 

See https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/166#issuecomment-1770987502 statement on the fact that there is a 6.0.x but no 5.7.1 for unknown reasons. 

Where is the best place to raise this possibly more general tagging issue?

**Comment by ckastner** [comment]
For the Debian packaging, I'd also appreciate a 5.7.1 tag. Thanks!

**Comment by BenWibking** [comment]
There's a tag now, so closing as fixed.
