### ISSUE TITLE
Link to "ROCm's package servers" is broken in README.md

### ISSUE THREAD

**Issue by vcanaa** [ROCmSoftwarePlatform/hipRAND#98]
**Describe the bug**
Link is broken as it reads:
>You can download pre-built packages from [ROCm's package servers](https://rocm.github.io/install.html#installing-from-amd-rocm-repositories), or by clicking the github releases tab (this option could have a newer version).

**Comment by stanleytsang-amd** [comment]
Thanks for reporting this; we will update the README and documentation with updated instructions.

**Comment by Naraenda** [comment]
This has been already fixed for a while.
